### ISSUE TITLE
Error while pushing on github

### ISSUE THREAD

**Issue by vjaykoogu** [chloerei/campo#27]
im trying to push on github and im getting this error message.

error: The requested URL returned error: 403 while accessing https://github.com/chloerei/campo.git/info/refs

**Comment by chloerei** [comment]
Which step you found this error?

**Comment by vjaykoogu** [comment]
while pushing on github....
eg: git push origin master

**Comment by chloerei** [comment]
You are not in collaborators so can not direct push to this repo.

Do you need fork? https://help.github.com/articles/fork-a-repo

**Comment by vjaykoogu** [comment]
no i want to push on my  new repository... i found y http://stackoverflow.com/a/7771927/840054

**Comment by chloerei** [comment]
So it solved?

**Comment by vjaykoogu** [comment]
no i remvd lines 

[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
[remote "origin"]
    fetch = +refs/heads/_:refs/remotes/origin/_
    url = https://github.com/jendewalt/yumhacker.git
[branch "master"]
    remote = origin
    merge = refs/heads/master

TO

---

[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true

but no luck brother... :(

**Comment by chloerei** [comment]
```
git remote add origin your_repo_url
```

**Comment by vjaykoogu** [comment]
ahh its works thanks bro.. but now while deploying

DEBUG[5b9108c4]     /usr/bin/env: git: No such file or directory
DEBUG[5b9108c4] Finished in 0.498 seconds with exit status 127 (failed).
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 162.243.74.66: exit

**Comment by chloerei** [comment]
Had you run `./script/setup.sh` in server side? And git should install manual in server side:

```
sudo apt-get install git
```

**Comment by vjaykoogu** [comment]
yep i did tat.. 

DEBUG[e095c1dd]     Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
DEBUG[e095c1dd]     ERROR: Repository not found.
DEBUG[e095c1dd]     fatal: The remote end hung up unexpectedly
DEBUG[e095c1dd] Finished in 1.650 seconds with exit status 128 (failed).
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 162.243.74.66: exit

**Comment by chloerei** [comment]
Edit git repo url in `config/deploy.rb` .

https://github.com/chloerei/campo/blob/master/config/deploy.rb#L5

**Comment by vjaykoogu** [comment]
yep done bro...

**Comment by chloerei** [comment]
Post complete logs.

`ERROR: ERROR: Repository not found.` means something config wrong....

**Comment by vjaykoogu** [comment]
DEBUG[e095c1dd] Running /usr/bin/env git ls-remote git@github.com:vijaykoogu/campo.git on 162.243.74.66
DEBUG[e095c1dd] Command: ( GIT_ASKPASS=/bin/echo GIT_SSH=/tmp/campo/git-ssh.sh /usr/bin/env git ls-remote git@github.com:vijaykoogu/campo.git )
DEBUG[e095c1dd]     Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
DEBUG[e095c1dd]     ERROR: Repository not found.
DEBUG[e095c1dd]     fatal: The remote end hung up unexpectedly
DEBUG[e095c1dd] Finished in 1.650 seconds with exit status 128 (failed).
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 162.243.74.66: exit
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:28:in `exit'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:28:in`block (4 levels) in <top (required)>'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/abstract.rb:85:in `with'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:27:in`block (3 levels) in <top (required)>'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in`run'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
SystemExit: exit
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:28:in`exit'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:28:in `block (4 levels) in <top (required)>'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/abstract.rb:85:in`with'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:27:in `block (3 levels) in <top (required)>'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in`instance_exec'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in`block (2 levels) in execute'
Tasks: TOP => git:check
(See full trace by running task with --trace)

**Comment by chloerei** [comment]
Maybe need SSH agent forwarding https://help.github.com/articles/using-ssh-agent-forwarding

Fast fix:

Edit .ssh/config in local, my example:

```
Host codecampo.com
  ForwardAgent yes
```

then add default ssh key to key chain:

```
$ ssh-add
```

Run this every time before `cap production deploy`

**Comment by vjaykoogu** [comment]
no luck.. i did everything... it still give me below error

DEBUG[13a9e02b] Command: ( GIT_ASKPASS=/bin/echo GIT_SSH=/tmp/campo/git-ssh.sh /usr/bin/env git ls-remote git@github.com:vijaykoogu/campo.git )
DEBUG[13a9e02b]     ERROR: Repository not found.
DEBUG[13a9e02b]     fatal: The remote end hung up unexpectedly
DEBUG[13a9e02b] Finished in 1.611 seconds with exit status 128 (failed).
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 162.243.74.66: exit
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:28:in `exit'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:28:in`block (4 levels) in <top (required)>'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/abstract.rb:85:in `with'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:27:in`block (3 levels) in <top (required)>'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in`run'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
SystemExit: exit
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:28:in`exit'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:28:in `block (4 levels) in <top (required)>'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/abstract.rb:85:in`with'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:27:in `block (3 levels) in <top (required)>'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in`instance_exec'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/home/qoogu/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in`block (2 levels) in execute'
Tasks: TOP => git:check
The deploy has failed with an error: #<SSHKit::Runner::ExecuteError: Exception while executing on host 162.243.74.66: exit>
*\* Invoke deploy:failed (first_time)
*\* Execute deploy:failed

**Comment by chloerei** [comment]
vijaykoogu is it typo?

**Comment by vjaykoogu** [comment]
sorry dint get u...

**Comment by vjaykoogu** [comment]
DEBUG[13a9e02b]     ERROR: Repository not found.
DEBUG[13a9e02b]     fatal: The remote end hung up unexpectedly

hope tis help

**Comment by chloerei** [comment]
Does it fixed? `vijaykoogu` => `vjaykoogu`

**Comment by vjaykoogu** [comment]
nop still above error :(

**Comment by chloerei** [comment]
Try to clone this repo in server by manual, check what's problem.

**Comment by vjaykoogu** [comment]
yep...

**Comment by KelvinMutuma** [comment]
Hey, I'm trying to update my app on the server and I'm getting this error

http://stackoverflow.com/questions/17846529/could-not-open-a-connection-to-your-authentication-agent

**Comment by chloerei** [comment]
@KelvinMutuma open a new issues and post more info.

**Comment by KelvinMutuma** [comment]
I had fully setup my app, capistrano server and target server and I pushed my app using cap production deploy a few days ago, I have changed nothing ever since but today I worked on my app and pushed some changes to the git master branch which is what I am deploying from, However when I run **cap production deploy** I get the following error

DEBUG[993beaec] Running /usr/bin/env [ -d ~/.rvm ] on abacusdev.cloudapp.net
DEBUG[993beaec] Command: [ -d ~/.rvm ]
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host abacusdev.cloudapp.net: agent could not sign data with requested identity
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/agent/socket.rb:118:in `sign'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/key_manager.rb:155:in`sign'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/methods/publickey.rb:20:in`block in authenticate'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/key_manager.rb:112:in `block in each_identity'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/key_manager.rb:104:in`each'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/key_manager.rb:104:in `each_identity'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/methods/publickey.rb:19:in`authenticate'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/session.rb:79:in `block in authenticate'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/session.rb:66:in`each'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/session.rb:66:in `authenticate'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh.rb:206:in`start'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:50:in `call'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:50:in`create_new_entry'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:22:in `checkout'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:179:in`with_ssh'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:131:in `block in _execute'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:128:in`tap'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:128:in `_execute'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:62:in`test'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/capistrano-rvm-0.1.1/lib/capistrano/tasks/rvm.rake:19:in `block (3 levels) in <top (required)>'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in`instance_exec'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in`block (2 levels) in execute'
Net::SSH::Authentication::AgentError: agent could not sign data with requested identity
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/agent/socket.rb:118:in `sign'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/key_manager.rb:155:in`sign'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/methods/publickey.rb:20:in`block in authenticate'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/key_manager.rb:112:in `block in each_identity'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/key_manager.rb:104:in`each'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/key_manager.rb:104:in `each_identity'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/methods/publickey.rb:19:in`authenticate'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/session.rb:79:in `block in authenticate'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/session.rb:66:in`each'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh/authentication/session.rb:66:in `authenticate'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/net-ssh-2.9.1/lib/net/ssh.rb:206:in`start'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:50:in `call'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:50:in`create_new_entry'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:22:in `checkout'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:179:in`with_ssh'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:131:in `block in _execute'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:128:in`tap'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:128:in `_execute'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:62:in`test'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/capistrano-rvm-0.1.1/lib/capistrano/tasks/rvm.rake:19:in `block (3 levels) in <top (required)>'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in`instance_exec'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/home/kelvin/.rvm/gems/ruby-2.1.1/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in`block (2 levels) in execute'
Tasks: TOP => rvm:hook
(See full trace by running task with --trace)

**Comment by KelvinMutuma** [comment]
My production.rb is as follows

set :stage, :production
set :deploy_user, "xxxxxx"
set :full_app_name, "#{fetch(:application)}_#{fetch(:stage)}"
server 'xxxxx.xxxxx.net', user: 'xxxxxx', roles: %w{web app db}, primary: true
set :deploy_to, "/home/#{fetch(:deploy_user)}/apps/#{fetch(:full_app_name)}"
set :rails_env, :production

**Comment by chloerei** [comment]
Logs shows you can not login to server `abacusdev.cloudapp.net`, have you try to login this server via ssh?

**Comment by KelvinMutuma** [comment]
My deploy.rb is as follows

lock '3.2.1'
set :application, 'nse_data'
set :repo_url, 'git@github.com:KelvinMutuma/abdv.git'
set :branch, "master"
set :scm, :git
set :format, :pretty
set :log_level, :debug
set :pty, true
set :linked_dirs, %w{bin log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system}
set :keep_releases, 5

namespace :deploy do

  desc 'Restart application'
  task :restart do
    on roles(:app), in: :sequence, wait: 5 do
      # Your restart mechanism here, for example:
      # execute :touch, release_path.join('tmp/restart.txt')
    end
  end

  after :publishing, :restart

  after :restart, :clear_cache do
    on roles(:web), in: :groups, limit: 3, wait: 10 do
      # Here we can do anything
    end
  end

My Gemfile is as follows

gem 'unicorn'
gem 'unicorn-rails'
group :development do
  # Use Capistrano for deployment
  gem 'capistrano', '~> 3.1'
  gem 'capistrano-rails', '~> 1.1.1'
  gem 'capistrano-bundler'
  gem 'capistrano-rvm', require: false
  gem 'capistrano-unicorn-nginx', '~> 2.0'
  gem 'capistrano-postgresql', '~> 3.0'
end

gem 'pg', group: :production

My Capfile

require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/unicorn_nginx'
require 'capistrano/postgresql'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails'
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }

**Comment by KelvinMutuma** [comment]
Yes I can

**Comment by KelvinMutuma** [comment]
I have sshed to server ryt now and it works

**Comment by chloerei** [comment]
@KelvinMutuma Sorry, I don't know how to solve it.

**Comment by KelvinMutuma** [comment]
Okay, Thanks. Let me battle with it

**Comment by KelvinMutuma** [comment]
@chloerei I just restarted my server and it worked. I'm not sure what the problem was though
